- alias: Automatic Updates
  triggers:
  - trigger: time
    at: 04:00:00
  actions:
  - action: update.install
    target:
      entity_id: '{{ states.update | map(attribute=''entity_id'') | select(''is_state'',
        ''on'') | list }}'
  id: b792fb1f2382432db2d67d66289a3c40
- id: '1739163441114'
  alias: Atmospheric Manager
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.office_air_quality_index
    below: 50
    id: turn_off
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - trigger: numeric_state
    entity_id:
    - sensor.office_air_quality_index
    above: 50
    id: turn_on
    for:
      hours: 0
      minutes: 1
      seconds: 0
  actions:
  - action: switch.{{ trigger.id if trigger.id is defined else 'toggle' }}
    target:
      entity_id: switch.air_filter
- id: '1759856160073'
  alias: Test Notification
  description: ''
  triggers: []
  conditions: []
  actions:
  - action: notify.send_message
    metadata: {}
    data:
      message: Test Notification
  mode: single
