---
# Loads default set of integrations. Do not remove.
default_config:

# Enable Home Assistant Cloud
cloud:

http:
  server_port: 80

# Enable auto configuration of bluetooth
bluetooth:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Notification groups
notify:
  - name: all_devices
    platform: group
    services:
      - service: persistent_notification
      - service: mobile_app_jason_s_phone

  - name: low_priority
    platform: group
    services:
      - service: persistent_notification

homeassistant:
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages

# Lovelace dashboards
lovelace:
  mode: storage
  dashboards: !include_dir_named dashboards
