---
# Loads default set of integrations. Do not remove.
default_config:

# Enable Home Assistant Cloud
cloud:

http:
  server_port: 80

# Enable auto configuration of bluetooth
bluetooth:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages
